$(function(){var flexContainer=$('div.flex-container')
var searchBox=$('.search-box')
var searchClose=$('.search-icon-close')
var searchInput=$('#search-input')
$('.menu-icon, .menu-icon-close').click(function(e){e.preventDefault()
e.stopPropagation()
flexContainer.toggleClass('active')})
flexContainer.click(function(e){if(flexContainer.hasClass('active')&&e.target.tagName!=='A'){flexContainer.removeClass('active')}})
$(window).keydown(function(e){if(e.key==='Escape'){if(flexContainer.hasClass('active')){flexContainer.removeClass('active')}else if(searchBox.hasClass('search-active')){searchBox.removeClass('search-active')}}})
$('.search-icon').click(function(e){e.preventDefault()
searchBox.toggleClass('search-active')
searchInput.focus()
if(searchBox.hasClass('search-active')){searchClose.click(function(e){e.preventDefault()
searchBox.removeClass('search-active')})}})})
